# Generated by Django 2.1 on 2019-04-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xinghao', models.CharField(max_length=32)),
                ('pinglei', models.CharField(max_length=68)),
                ('new_old', models.CharField(max_length=16)),
                ('dingwei', models.CharField(max_length=64)),
                ('pingming', models.CharField(max_length=128)),
                ('cpu', models.CharField(max_length=16)),
                ('xianka', models.CharField(max_length=64)),
                ('neicun', models.CharField(max_length=32)),
                ('ssd', models.CharField(max_length=64)),
                ('hhd', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=128, null=True)),
                ('config', models.TextField(null=True)),
                ('pn', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
