# Generated by Django 2.1 on 2019-04-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_kc_erp_ydh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kc_Erp_Zksp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riqi', models.DateField(verbose_name='日期')),
                ('zhjhrq', models.CharField(max_length=32, verbose_name='最后进货日期')),
                ('spjdrq', models.CharField(max_length=32, verbose_name='商品建档日期')),
                ('kufang', models.CharField(max_length=32, verbose_name='库房')),
                ('hl', models.CharField(max_length=32, verbose_name='货拉')),
                ('lbmc', models.CharField(max_length=64, verbose_name='类别名称')),
                ('spbm', models.CharField(max_length=64, verbose_name='商品编码')),
                ('spmc', models.CharField(max_length=256, verbose_name='商品名称')),
                ('xh', models.CharField(max_length=64, verbose_name='型号')),
                ('guige', models.CharField(max_length=256, verbose_name='规格')),
                ('pinpai', models.CharField(max_length=64, verbose_name='品牌')),
                ('zks', models.FloatField(verbose_name='在库数')),
                ('qjxss', models.FloatField(verbose_name='区间销售数')),
            ],
        ),
    ]
